modLoader="javafml"
loaderVersion="[43,)"
license="All Rights Reserved"

[[mods]]
modId="ls_furniture"
version="0.4.1"
displayName="LYIVX's Furniture"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://curseforge.com/minecraft/mc-mods/lyivxs-furniture"
logoFile="logo.png"
authors="LYIVX, MCreator"
description="Furniture Mod"

[[dependencies.ls_furniture]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"



[[dependencies.ls_furniture]]
    modId="jade"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ls_furniture]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ls_furniture]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

