modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="ls_furniture"
version="0.6.2"
displayName="LYIVX's Furniture"
displayURL="https://curseforge.com/minecraft/mc-mods/lyivxs-furniture"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="LYIVX, MCreator"
description="Furniture Mod"

[[dependencies.ls_furniture]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



[[dependencies.ls_furniture]]
    modId="fusion"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ls_furniture]]
    modId="use_compiled_mods"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ls_furniture]]
    modId="jade"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ls_furniture]]
    modId="patchouli"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ls_furniture]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

